import { describe, it, expect, vi, afterEach } from 'vitest'
import { useWorkspace } from '../src/workspace'
import { request } from '../src/api'
import { matchesStatus } from '../src/domain'
const ticket={id:'SW-001',title:'Title',prompt:'Prompt',provider:'demo',status:'todo',images:[],response:'',files:[],created_at:'',queued_at:''}
const response=(value:any,ok=true,status=200)=>({ok,status,json:async()=>value})
afterEach(()=>vi.unstubAllGlobals())
describe('workspace logic',()=>{
 it('tracks failed refresh and retries',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValueOnce(new Error('offline')).mockResolvedValue(response([ticket])));const w=useWorkspace();await w.refresh();expect(w.online.value).toBe(false);await w.refresh();expect(w.online.value).toBe(true)})
 it('validates draft, edits and resets selection',async()=>{const w=useWorkspace();w.newTicket();await w.save();expect(w.error.value).toContain('title');w.draft.value.title='test';await w.save();expect(w.error.value).toContain('prompt');w.tickets.value=[ticket as any];w.select(ticket as any);expect(w.editable.value).toBe(true);w.newTicket();expect(w.selected.value).toBeUndefined()})
 it('runs dirty prompt after saving and reports errors',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response(ticket)));const w=useWorkspace();w.select(ticket as any);w.draft.value.prompt='New';await w.run();expect(fetch).toHaveBeenCalledWith('/api/tickets/SW-001',expect.objectContaining({method:'PATCH'}));vi.stubGlobal('fetch',vi.fn().mockRejectedValue('failure'));await w.save();expect(w.error.value).toBe('Something went wrong.')})
 it('drops only todo tickets',async()=>{let fetchCalls=0;vi.stubGlobal('fetch',vi.fn(async(url:string,options:any)=>{if(url.endsWith('/groups'))return response([]);if(options.method==='POST')return response(ticket);return response([{...ticket,status:fetchCalls++ ? 'queued':'todo'}])}));const w=useWorkspace();await w.refresh();await w.drop('missing');await w.drop(ticket.id);expect(w.selected.value?.status).toBe('queued');await w.drop(ticket.id);expect(fetch).toHaveBeenCalledTimes(5)})
 it('pastes and limits images',async()=>{const w=useWorkspace();w.newTicket();const make=(file:File)=>({clipboardData:{files:[file]},preventDefault:vi.fn()}) as any;await w.paste(make(new File(['x'],'a.svg',{type:'image/svg+xml'})));expect(w.error.value).toContain('5 MB');const event=make(new File(['pixels'],'a.png',{type:'image/png'}));await w.paste(event);expect(w.draft.value.images[0]).toContain('data:image/png;base64');expect(event.preventDefault).toHaveBeenCalled();w.draft.value.images=Array(6).fill('a');await w.paste(event);expect(w.error.value).toContain('6 images');await w.paste({clipboardData:{files:[]}} as any);w.select({...ticket,status:'done'} as any);await w.paste(event);expect(w.draft.value.images).toHaveLength(0)})
 it('handles image read errors',async()=>{vi.stubGlobal('FileReader',class {onerror:any;readAsDataURL(){this.onerror(new Error('read failed'))}});const w=useWorkspace();w.newTicket();await w.paste({clipboardData:{files:[new File(['x'],'a.png',{type:'image/png'})]},preventDefault(){}} as any);expect(w.error.value).toContain('Could not read')})
 it('reports readable and validation API failures',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValueOnce(response({detail:'Not connected'},false,409)).mockResolvedValueOnce(response({detail:[]},false,422)).mockResolvedValueOnce({ok:false,status:500,json:async()=>{throw new Error()}}));await expect(request('/tickets')).rejects.toThrow('Not connected');await expect(request('/tickets')).rejects.toThrow('422');await expect(request('/tickets')).rejects.toThrow('500')})
 it('matches active and exact status',()=>{expect(matchesStatus('running','active')).toBe(true);expect(matchesStatus('failed','active')).toBe(true);expect(matchesStatus('todo','active')).toBe(false);expect(matchesStatus('done','done')).toBe(true)})
})
