import { describe, it, expect, vi, beforeEach } from 'vitest'
import { mount, flushPromises } from '@vue/test-utils'
import App from '../src/App.vue'
const ticket={id:'SW-001',title:'Navigation',prompt:'Add links',provider:'demo',images:[],status:'todo',files:[],response:'',created_at:'2026-10-05'}
let data:any[]
beforeEach(()=>{data=[{...ticket}];vi.stubGlobal('fetch',vi.fn(async(url:string,options:any)=>{if(url.startsWith('/api/projects'))return {ok:true,json:async()=>[{id:'default',name:'My first project',description:'',deleted:false}]};if(url.endsWith('/project'))return {ok:true,json:async()=>({name:'My first project',description:''})};if(url.endsWith('/config'))return {ok:true,json:async()=>({providers:[{id:'demo',name:'Demo agent',available:true}],workspace_roots:[],timeout_seconds:600})};if(url.endsWith('/groups')||url.endsWith('/workspaces')||url.endsWith('/runs')||url.endsWith('/events'))return {ok:true,json:async()=>[]};if(options?.method==='POST'&&url.endsWith('/run'))data[0]={...data[0],status:'queued'};if(options?.method==='POST'&&!url.endsWith('/run'))data.push({...ticket,...JSON.parse(options.body),id:'SW-002'});if(options?.method==='PATCH')data[0]={...data[0],...JSON.parse(options.body)};return {ok:true,json:async()=>JSON.parse(JSON.stringify(options?.method!=='GET'?data.at(-1):data))}}))})
describe('workspace',()=>{
 it('loads and selects a ticket',async()=>{const w=mount(App);await flushPromises();expect(w.text()).toContain('Navigation');await w.get('[data-ticket="SW-001"]').trigger('click');expect(w.get('textarea').element.value).toBe('Add links');w.unmount()})
 it('creates a ticket',async()=>{const w=mount(App);await flushPromises();await w.get('[data-testid="new-ticket"]').trigger('click');await w.get('[aria-label="Ticket title"]').setValue('New feature');await w.get('textarea').setValue('Build it');await w.get('[data-testid="save-ticket"]').trigger('click');await flushPromises();expect(w.text()).toContain('New feature');w.unmount()})
 it('saves edits and runs a ticket',async()=>{const w=mount(App);await flushPromises();await w.get('[data-ticket="SW-001"]').trigger('click');await w.get('textarea').setValue('Add better links');await w.get('[data-testid="save-ticket"]').trigger('click');await flushPromises();expect(data[0].prompt).toBe('Add better links');await w.get('[data-testid="run-ticket"]').trigger('click');await flushPromises();expect(w.text()).toContain('Queued');w.unmount()})
 it('shows completed response and files',async()=>{data=[{...ticket,status:'done',response:'Simulated response',files:[{path:'file.vue',additions:1,deletions:1,diff:'+new\n-old'}]}];const w=mount(App);await flushPromises();await w.get('[data-ticket="SW-001"]').trigger('click');expect(w.text()).toContain('Simulated response');expect(w.text()).toContain('file.vue');w.unmount()})
})

describe('workspace interactions',()=>{
 it('filters, creates through lane and opens help',async()=>{const w=mount(App);await flushPromises();await w.get('[aria-label="Search tickets"]').setValue('nothing');expect(w.find('[data-ticket]').exists()).toBe(false);await w.get('[aria-label="Filter status"]').trigger('click',{button:0,ctrlKey:false});await flushPromises();(document.querySelector('[data-status="done"]') as HTMLElement).click();await flushPromises();await w.get('[aria-label="Help"]').trigger('click');await flushPromises();expect(document.body.textContent).toContain('A ticket is your starting point');const close=document.querySelector('[aria-label="Close preview"]') as HTMLButtonElement;close.click();await flushPromises();await w.get('[aria-label="How it works"]').trigger('click');await flushPromises();(document.querySelector('[aria-label="Close preview"]') as HTMLButtonElement).click();await flushPromises();await w.get('[aria-label="Create ticket in Todo"]').trigger('click');expect(w.get('[aria-label="Ticket title"]').exists()).toBe(true);await w.get('.add-ticket').trigger('click');w.unmount()})
 it('drags into active lane',async()=>{const w=mount(App);await flushPromises();const dt={setData:vi.fn(),getData:()=>ticket.id};await w.get('[data-ticket]').trigger('dragstart',{dataTransfer:dt});expect(dt.setData).toHaveBeenCalledWith('text/plain',ticket.id);await w.get('[data-lane="active"]').trigger('dragover');await w.get('[data-lane="active"]').trigger('dragleave');await w.get('[data-lane="active"]').trigger('drop',{dataTransfer:dt});await flushPromises();expect(w.text()).toContain('Queued');w.unmount()})
 it('previews a file and image and removes attachment',async()=>{const img='data:image/png;base64,cGl4ZWxz';data=[{...ticket,status:'todo',images:[img],files:[{path:'file.vue',additions:1,deletions:1,diff:'+new\n-old'}]}];const w=mount(App);await flushPromises();await w.get('[data-ticket]').trigger('click');await w.get('[aria-label="Preview attached image"]').trigger('click');await flushPromises();expect(document.querySelector('.preview-image')).not.toBeNull();(document.querySelector('[aria-label="Close preview"]') as HTMLButtonElement).click();await flushPromises();await w.get('[aria-label="Remove image"]').trigger('click');expect(w.find('.attachment').exists()).toBe(false);await w.get('.file-row').trigger('click');await flushPromises();expect(document.querySelector('.diff')?.textContent).toContain('+new');(document.querySelector('[aria-label="Close preview"]') as HTMLButtonElement).click();await flushPromises();await w.get('textarea').trigger('paste',{clipboardData:{files:[]}});await w.get('#agent').setValue('demo');w.unmount()})
 it('opens other help actions and offline retry',async()=>{vi.stubGlobal('fetch',vi.fn().mockRejectedValue(new Error('offline')));const w=mount(App);await flushPromises();await w.get('.connection-error button').trigger('click');await w.get('.top-help').trigger('click');await flushPromises();(document.querySelector('[aria-label="Close preview"]') as HTMLButtonElement).click();await flushPromises();await w.get('.demo-strip button').trigger('click');await flushPromises();(document.querySelector('[aria-label="Close preview"]') as HTMLButtonElement).click();await flushPromises();await w.get('.inspector-empty button').trigger('click');w.unmount()})
})
