import { test, expect } from '@playwright/test'
async function dragWithinLane(page:any,source:any,target:any) {
 await source.scrollIntoViewIfNeeded()
 const start=await source.boundingBox()
 await page.mouse.move(start.x+20,start.y+20);await page.mouse.down()
 // Start the native drag before scrolling the same lane to its destination.
 await page.mouse.move(start.x+30,start.y+30,{steps:5})
 await target.scrollIntoViewIfNeeded()
 const end=await target.boundingBox()
 await page.mouse.move(end.x+20,end.y+end.height/2,{steps:10});await page.mouse.up()
}
async function create(page:any,title:string) {
 await page.getByTestId('new-ticket').click()
 await page.getByLabel('Ticket title').fill(title)
 await page.getByLabel('Prompt', {exact:true}).fill('Create a responsive and accessible feature.')
 await page.getByTestId('save-ticket').click()
 await expect(page.locator('.ticket').filter({hasText:title})).toBeVisible()
}
test('create, edit, run and review diff',async({page})=>{
 await page.setViewportSize({width:1440,height:900})
 await page.goto('/')
 await page.locator('[data-ticket="SW-003"]').click()
 await page.screenshot({path:'../docs/workspace.png',fullPage:true})
 const title=`Feature ${Date.now()}`
 await create(page,title)
 await page.getByLabel('Prompt',{exact:true}).fill('Add accessible keyboard navigation.')
 await page.getByTestId('save-ticket').click()
 await page.reload()
 await page.locator('.ticket').filter({hasText:title}).click()
 await expect(page.getByLabel('Prompt',{exact:true})).toHaveValue('Add accessible keyboard navigation.')
 await page.getByTestId('run-ticket').click()
 await expect(page.locator('[data-lane="active"] .ticket').filter({hasText:title})).toBeVisible()
 await expect(page.getByLabel('Prompt',{exact:true})).toHaveAttribute('readonly')
 await expect(page.locator('[data-lane="done"] .ticket').filter({hasText:title})).toBeVisible({timeout:10000})
 await expect(page.locator('.response-text')).toContainText('Simulated run complete')
 await page.getByRole('button',{name:/src\/components\/Feature.vue/}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.locator('.diff .added').first()).toContainText('+++')
 await page.getByRole('button',{name:'Close preview'}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
})
test('drag into progress triggers queued work',async({page})=>{
 await page.goto('/')
 const first=`Drag first ${Date.now()}`,second=`Drag next ${Date.now()}`
 await create(page,first);await create(page,second)
 await page.locator('.ticket').filter({hasText:first}).dragTo(page.locator('[data-lane="active"]'))
 await page.locator('.ticket').filter({hasText:second}).dragTo(page.locator('[data-lane="active"]'))
 await expect(page.locator('[data-lane="active"] .ticket').filter({hasText:second})).toContainText('Queued')
 await expect(page.locator('[data-lane="done"] .ticket').filter({hasText:second})).toBeVisible({timeout:15000})
})
test('queue reaches Done when a live event connection stalls',async({page})=>{
 await page.addInitScript(()=>{
  window.EventSource=class {
   onopen:(()=>void)|null=null
   onmessage=null
   onerror=null
   constructor(){setTimeout(()=>this.onopen?.(),0)}
   close(){}
  } as unknown as typeof EventSource
 })
 await page.goto('/')
 const first=`Stalled first ${Date.now()}`,second=`Stalled next ${Date.now()}`
 await create(page,first);await page.getByTestId('run-ticket').click()
 await create(page,second);await page.getByTestId('run-ticket').click()
 await expect(page.locator('[data-lane="active"] .ticket').filter({hasText:second})).toContainText('Queued')
 await expect(page.locator('[data-lane="done"] .ticket').filter({hasText:first})).toBeVisible({timeout:15000})
 await expect(page.locator('[data-lane="done"] .ticket').filter({hasText:second})).toBeVisible({timeout:15000})
 await expect(page.locator('.response-text')).toContainText('Simulated run complete')
 await expect(page.locator('.task-heading .status-pill')).toHaveText('Done')
})
test('paste image, enlarge, remove; validation and search',async({page})=>{
 await page.goto('/')
 await page.getByTestId('new-ticket').click()
 await page.getByTestId('save-ticket').click()
 await expect(page.getByRole('alert')).toContainText('Give your ticket a title')
 await page.getByLabel('Prompt',{exact:true}).evaluate((element:HTMLTextAreaElement)=>{
 const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0ioAAAAASUVORK5CYII='),c=>c.charCodeAt(0))
 const clipboardData=new DataTransfer();clipboardData.items.add(new File([bytes],'reference.png',{type:'image/png'}))
 element.dispatchEvent(new ClipboardEvent('paste',{clipboardData,bubbles:true}))
 })
 await page.getByRole('button',{name:'Preview attached image'}).click()
 await expect(page.getByRole('dialog')).toBeVisible()
 await expect(page.getByAltText('Full size prompt reference')).toBeVisible()
 await page.keyboard.press('Escape')
 await page.getByRole('button',{name:'Remove image'}).click()
 await expect(page.getByAltText('Prompt reference',{exact:true})).not.toBeVisible()
 await page.getByLabel('Search tickets').fill('zzzz-unmatched')
 await expect(page.locator('.ticket')).toHaveCount(0)
 await page.getByLabel('Search tickets').fill('')
 await page.getByRole('button',{name:'Filter status',exact:true}).click()
 await page.getByRole('menuitemradio',{name:'Done',exact:true}).click()
 await expect(page.locator('[data-lane="todo"] .ticket')).toHaveCount(0)
})
test('small viewport keeps board and inspector usable',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/')
 await page.getByTestId('new-ticket').click()
 await expect(page.getByLabel('Ticket title')).toBeVisible()
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth)
 expect(overflow).toBe(false)
})
test('cancel, retry and review previous attempts',async({page})=>{
 await page.goto('/')
 const title=`Retry ${Date.now()}`
 await create(page,title)
 await page.getByTestId('run-ticket').click()
 await page.getByRole('button',{name:'Cancel run',exact:true}).click()
 await expect(page.locator('.task-heading .status-pill')).toHaveText('Cancelled')
 await page.getByRole('button',{name:'Retry ticket',exact:true}).click()
 await expect(page.locator('[data-lane="done"] .ticket').filter({hasText:title})).toBeVisible({timeout:10000})
 await expect(page.locator('.history-row')).toHaveCount(2)
 await page.locator('.history-row').last().click()
 await expect(page.getByRole('dialog')).toContainText(/Cancelled before execution|Run cancelled/)
 await page.keyboard.press('Escape')
 await page.locator('.history-row').first().click()
 await expect(page.getByRole('dialog')).toContainText('Simulated run complete')
 await page.locator('.run-review .file-row').first().click()
 await expect(page.locator('.run-review .diff')).toBeVisible()
})
test('repository settings explain server credentials and validate paths',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:'Repository settings',exact:true}).click()
 await expect(page.getByRole('dialog')).toContainText('CODEX_API_KEY')
 await page.getByLabel('Repository name').fill('Invalid project')
 await page.getByLabel('Repository path').fill('/this-repo-does-not-exist')
 await page.getByRole('button',{name:'Register repository',exact:true}).click()
 await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
 await page.keyboard.press('Escape')
})
test('groups follow tickets through runs and support edit, collapse and removal',async({page})=>{
 await page.setViewportSize({width:1440,height:900})
 await page.goto('/')
 await page.getByRole('button',{name:'Add group',exact:true}).click()
 await page.getByLabel('Group name',{exact:true}).fill('Navbar')
 await page.getByRole('button',{name:'Use blue colour',exact:true}).click()
 await page.getByRole('button',{name:'Create group',exact:true}).click()
 const todo=page.getByRole('region',{name:'Navbar group in Todo',exact:true})
 await todo.getByRole('button',{name:'Add ticket to Navbar',exact:true}).click()
 await page.getByLabel('Ticket title').fill('Grouped navigation')
 await page.getByLabel('Prompt',{exact:true}).fill('Build grouped navigation')
 await page.getByTestId('save-ticket').click()
 await expect(todo.locator('.ticket')).toBeVisible()
 await todo.getByRole('button',{name:'Minimise Navbar in Todo'}).click()
 await expect(todo.locator('.ticket')).toHaveCount(0)
 await todo.getByRole('button',{name:'Expand Navbar in Todo'}).click()
 await todo.locator('.ticket').dragTo(page.locator('[data-lane="active"]'))
 const done=page.getByRole('region',{name:'Navbar group in Done',exact:true})
 await expect(done.locator('.ticket')).toBeVisible({timeout:10000})
 await done.locator('summary').click()
 await done.getByRole('button',{name:'Edit Navbar',exact:true}).click()
 await page.getByLabel('Group name',{exact:true}).fill('Navigation')
 await page.getByLabel('Custom group colour').fill('#edce82')
 await page.getByRole('button',{name:'Save group',exact:true}).click()
 await page.reload()
 const renamed=page.getByRole('region',{name:'Navigation group in Done',exact:true})
 await expect(renamed.locator('.ticket')).toContainText('Grouped navigation')
 await expect(renamed).toHaveCSS('--group-color','#edce82')
 await expect(renamed.locator('.group-header')).toHaveCSS('color','rgb(0, 0, 0)')
 await page.screenshot({path:'../docs/groups.png',fullPage:true})
 await renamed.locator('.ticket').click()
 await page.getByLabel('Group',{exact:true}).selectOption('')
 await expect(renamed).toHaveCount(0)
 const remaining=page.getByRole('region',{name:'Navigation group in Todo',exact:true})
 await remaining.locator('summary').click()
 await remaining.getByRole('button',{name:'Remove Navigation',exact:true}).click()
 await expect(remaining).toHaveCount(0)
 await expect(page.locator('.ticket').filter({hasText:'Grouped navigation'})).toBeVisible()
})
test('drag tickets into, between and out of groups without changing execution state',async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.goto('/')
 for(const name of ['Drag alpha','Drag beta']) {
  await page.getByRole('button',{name:'Add group',exact:true}).click()
  await page.getByLabel('Group name',{exact:true}).fill(name)
  await page.getByRole('button',{name:'Create group',exact:true}).click()
 }
 const alpha=page.getByRole('region',{name:'Drag alpha group in Todo',exact:true})
 const beta=page.getByRole('region',{name:'Drag beta group in Todo',exact:true})
 const title=`Regroup ${Date.now()}`
 await create(page,title)
 await page.getByLabel('Prompt',{exact:true}).fill('Keep my unsaved prompt')
 await dragWithinLane(page,page.locator('.ticket').filter({hasText:title}),alpha.locator('.group-header'))
 await expect(alpha.locator('.ticket')).toContainText(title)
 await expect(page.getByLabel('Prompt',{exact:true})).toHaveValue('Keep my unsaved prompt')
 await expect(page.getByLabel('Group',{exact:true})).toHaveValue(await alpha.getAttribute('data-group') as string)
 await beta.getByRole('button',{name:'Minimise Drag beta in Todo'}).click()
 await dragWithinLane(page,alpha.locator('.ticket'),beta.locator('.group-header'))
 await beta.getByRole('button',{name:'Expand Drag beta in Todo'}).click()
 await expect(beta.locator('.ticket')).toContainText(title)
 await expect(page.locator('.ungroup-drop')).toHaveCount(0)
 await dragWithinLane(page,beta.locator('.ticket'),page.locator('[data-lane="todo"] .lane-header'))
 await expect(page.locator('[data-lane="todo"] > .lane-cards > .ticket').filter({hasText:title})).toBeVisible()
 await expect(page.getByLabel('Group',{exact:true})).toHaveValue('')
 await page.getByTestId('save-ticket').click();await page.reload()
 await expect(page.locator('[data-lane="todo"] > .lane-cards > .ticket').filter({hasText:title})).toBeVisible()
 await page.locator('.ticket').filter({hasText:title}).click();await page.getByTestId('run-ticket').click()
 const completed=page.locator('[data-lane="done"] .ticket').filter({hasText:title})
 await expect(completed).toBeVisible({timeout:10000})
 await dragWithinLane(page,completed,alpha.locator('.group-header'))
 const doneAlpha=page.getByRole('region',{name:'Drag alpha group in Done',exact:true})
 await expect(doneAlpha.locator('.ticket')).toContainText(title)
 await expect(page.locator('.task-heading .status-pill')).toHaveText('Done')
 await page.reload();await expect(doneAlpha.locator('.ticket')).toContainText(title)
 await dragWithinLane(page,doneAlpha.locator('.ticket'),page.locator('[data-lane="done"] .lane-header'))
 await expect(page.locator('[data-lane="done"] > .lane-cards > .ticket').filter({hasText:title})).toBeVisible()
 await page.locator('[data-lane="done"] > .lane-cards > .ticket').filter({hasText:title}).click()
 await expect(page.locator('.task-heading .status-pill')).toHaveText('Done')
 await page.screenshot({path:'../docs/group-drag.png',fullPage:true})
})
test('run group queues saved prompts in order and completes the sequence',async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.goto('/')
 await page.getByRole('button',{name:'Add group',exact:true}).click()
 await page.getByLabel('Group name',{exact:true}).fill('Sequence')
 await page.getByRole('button',{name:'Create group',exact:true}).click()
 const todo=page.getByRole('region',{name:'Sequence group in Todo',exact:true})
 for(const title of ['Sequence first','Sequence second']) {
  await todo.getByRole('button',{name:'Add ticket to Sequence',exact:true}).click()
  await page.getByLabel('Ticket title').fill(title);await page.getByLabel('Prompt',{exact:true}).fill(title)
  await page.getByTestId('save-ticket').click();await expect(todo.locator('.ticket').filter({hasText:title})).toBeVisible()
 }
 await todo.locator('summary').click();await todo.getByRole('button',{name:'Run Sequence group',exact:true}).click()
 const active=page.getByRole('region',{name:'Sequence group in Doing',exact:true})
 await expect(active.locator('.ticket').filter({hasText:'Sequence second'})).toContainText('Queued')
 await expect(active.locator('.ticket').filter({hasText:'Sequence second'}).locator('[role=progressbar]')).toHaveAttribute('aria-valuenow','0')
 await expect(active.locator('.ticket').filter({hasText:'Sequence first'}).locator('[role=progressbar]')).toHaveAttribute('aria-valuetext','Agent is working')
 const done=page.getByRole('region',{name:'Sequence group in Done',exact:true})
 await expect(done.locator('.ticket').filter({hasText:'Sequence first'})).toBeVisible({timeout:10000})
 await expect(active.locator('.ticket').filter({hasText:'Sequence second'})).toBeVisible()
 await expect(done.locator('.ticket')).toHaveCount(2,{timeout:10000})
 await expect(done.locator('.completion-mark')).toHaveCount(2)
 await expect(done.locator('[role=progressbar]')).toHaveCount(0)
 await done.locator('.ticket').filter({hasText:'Sequence second'}).click()
 await page.locator('.history-row').first().click();await expect(page.getByRole('dialog')).toContainText('Tests: simulated')
 await page.keyboard.press('Escape')
 await todo.locator('summary').click();await expect(todo.getByRole('button',{name:'Run Sequence group',exact:true})).toBeDisabled()
})
test('edits project title and description and uses a keyboard-accessible status menu',async({page})=>{
 await page.setViewportSize({width:1440,height:900});await page.goto('/')
 await page.getByRole('button',{name:'Edit project',exact:true}).click()
 await page.getByLabel('Project title',{exact:true}).fill('Prompt workspace')
 await page.getByLabel('Project description',{exact:true}).fill('Build software through grouped prompts.\nReview each result before continuing.')
 await page.getByRole('button',{name:'Save project',exact:true}).click()
 await expect(page.getByRole('dialog')).not.toBeVisible()
 await expect(page.getByRole('heading',{level:1})).toHaveText('Prompt workspace')
 await expect(page.locator('.project-description')).toContainText('Build software through grouped prompts.')
 await page.reload()
 await expect(page.getByRole('heading',{level:1})).toHaveText('Prompt workspace')
 await expect(page.locator('.breadcrumb .project-switch')).toHaveText('Prompt workspace')
 const filter=page.getByRole('button',{name:'Filter status',exact:true})
 await filter.focus();await page.keyboard.press('ArrowDown')
 await expect(page.getByRole('menu')).toHaveClass(/menu-surface/)
 await page.getByRole('menuitemradio',{name:'Todo',exact:true}).click()
 await expect(filter).toHaveText('Todo')
 await expect(page.locator('[data-lane="done"] .ticket')).toHaveCount(0)
 await filter.click();await page.keyboard.press('Escape');await expect(page.getByRole('menu')).not.toBeVisible();await expect(filter).toBeFocused()
 const padding=await page.getByLabel('Search tickets').evaluate(element=>{const style=getComputedStyle(element);return [style.paddingLeft,style.paddingRight]})
 expect(padding).toEqual(['10px','10px'])
 await page.getByRole('button',{name:'Edit project',exact:true}).click();await page.getByLabel('Project description',{exact:true}).fill('');await page.getByRole('button',{name:'Save project',exact:true}).click()
 await expect(page.getByRole('button',{name:'Add a project description',exact:true})).toBeVisible()
})
test('manage isolated projects, delete tickets and restore deleted work',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/')
 const original=await page.locator('h1').innerText()
 const cover=await page.screenshot()
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'New project',exact:true}).click()
 await page.getByLabel('Project title',{exact:true}).fill('Inventory app')
 await page.getByLabel('Project description',{exact:true}).fill('Manage the stock room')
 await page.locator('#project-screenshot-file').setInputFiles({name:'project.png',mimeType:'image/png',buffer:cover})
 await expect(page.locator('.project-screenshot img')).toBeVisible()
 await page.getByRole('button',{name:'Create project',exact:true}).click()
 await expect(page.locator('h1')).toHaveText('Inventory app')
 await expect(page.locator('.ticket')).toHaveCount(0)
 await expect(page.locator('.projects-page')).toBeVisible()
 await expect(page.locator('.dialog-overlay')).toHaveCount(0)
 await expect(page.locator('.project-card').filter({hasText:'Inventory app'}).locator('img')).toBeVisible()
 await page.getByRole('button',{name:'Edit Inventory app',exact:true}).click()
 await page.getByLabel('Project title',{exact:true}).fill('Stock manager')
 await page.getByRole('button',{name:'Save project',exact:true}).click()
 await expect(page.locator('h1')).toHaveText('Stock manager')
 await page.getByRole('button',{name:'Back to board',exact:true}).click()
 await create(page,'Stock count')
 await page.getByRole('button',{name:'Delete ticket',exact:true}).click()
 await expect(page.locator('.ticket')).toHaveCount(0)
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'Restore Stock count',exact:true}).click()
 await page.getByRole('button',{name:'Back to board',exact:true}).click()
 await expect(page.locator('.ticket')).toContainText('Stock count')
 await page.locator('.ticket').click();await page.getByTestId('run-ticket').click()
 await expect(page.getByRole('button',{name:'Delete ticket',exact:true})).toBeDisabled()
 await expect(page.locator('[data-lane="done"] .ticket')).toBeVisible({timeout:10000})
 await page.getByRole('button',{name:'Delete ticket',exact:true}).click()
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'Restore Stock count',exact:true}).click()
 await page.getByRole('button',{name:`Open ${original}`,exact:true}).click()
 await expect(page.locator('.ticket').filter({hasText:'Stock count'})).toHaveCount(0)
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'Open Stock manager',exact:true}).click()
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'Delete Stock manager',exact:true}).click()
 await expect(page.locator('h1')).toHaveText(original)
 await expect(page.getByRole('button',{name:'Restore Stock manager',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Restore Stock manager',exact:true}).click()
 await page.getByRole('button',{name:'Back to board',exact:true}).click()
 await page.reload()
 await expect(page.locator('h1')).toHaveText('Stock manager')
 await page.locator('.ticket').click()
 await expect(page.locator('.response-text')).toContainText('Simulated run complete')
 await expect(page.locator('.history-row')).toHaveCount(1)
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await expect(page.getByRole('button',{name:'Edit Stock manager',exact:true})).toBeEnabled()
 await expect(page.locator('.project-card').filter({hasText:'Stock manager'}).locator('img')).toBeVisible()
 await page.screenshot({path:'../docs/projects.png',fullPage:true})
})

test('multiselect ranges and individual tickets with confirmed recoverable deletion',async({page})=>{
 test.setTimeout(60000)
 await page.setViewportSize({width:1440,height:1000});await page.goto('/')
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'New project',exact:true}).click()
 await page.getByLabel('Project title',{exact:true}).fill('Bulk selection project')
 await page.getByRole('button',{name:'Create project',exact:true}).click()
 await page.getByRole('button',{name:'Back to board',exact:true}).click()
 await page.getByRole('button',{name:'Add group',exact:true}).click()
 await page.getByLabel('Group name',{exact:true}).fill('Bulk group')
 await page.getByRole('button',{name:'Create group',exact:true}).click()
 for(let i=0;i<12;i++){
  await create(page,`Bulk task ${i}`)
  if(i<2){const option=page.locator('#ticket-group option').filter({hasText:'Bulk group'});await page.locator('#ticket-group').selectOption(await option.getAttribute('value') as string);await page.getByTestId('save-ticket').click()}
 }
 const card=(i:number)=>page.locator('.ticket').filter({has:page.getByText(`Bulk task ${i}`,{exact:true})})
 await card(0).click();await card(10).click({modifiers:['Shift']})
 await expect(page.locator('.ticket[aria-pressed="true"]')).toHaveCount(11)
 await expect(page.getByRole('toolbar',{name:'Selected ticket actions'})).toContainText('11 tickets selected')
 await card(4).click({modifiers:['Control']});await expect(page.locator('.ticket[aria-pressed="true"]')).toHaveCount(10)
 await card(11).click({modifiers:['Control']});await expect(page.locator('.ticket[aria-pressed="true"]')).toHaveCount(11)
 await card(4).click({modifiers:['Meta']});await expect(page.locator('.ticket[aria-pressed="true"]')).toHaveCount(12)
 await page.getByRole('button',{name:'Delete all',exact:true}).click()
 await expect(page.getByRole('dialog',{name:'Delete 12 selected tickets?'})).toBeVisible()
 await page.getByRole('button',{name:'Cancel',exact:true}).click();await expect(page.locator('.ticket')).toHaveCount(12)
 await page.screenshot({path:'../docs/multiselect.png',fullPage:true})
 await page.getByRole('button',{name:'Delete all',exact:true}).click()
 await page.getByRole('button',{name:'Confirm delete all',exact:true}).click()
 await expect(page.locator('.ticket')).toHaveCount(0)
 await expect(page.getByRole('toolbar',{name:'Selected ticket actions'})).toHaveCount(0)
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'Restore Bulk task 0',exact:true}).click()
 await page.getByRole('button',{name:'Back to board',exact:true}).click()
 await expect(card(0)).toBeVisible()
})

test('project dropdown lists and highlights projects, switches boards and guards drafts',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});await page.goto('/')
 const original=await page.locator('h1').innerText()
 await page.getByRole('button',{name:'Workspace',exact:true}).click()
 await page.getByRole('button',{name:'New project',exact:true}).click()
 await page.getByLabel('Project title',{exact:true}).fill('Dropdown project')
 await page.getByRole('button',{name:'Create project',exact:true}).click()
 await page.getByRole('button',{name:'Switch project',exact:true}).click()
 const current=page.getByRole('menuitemradio',{name:'Dropdown project Current',exact:true})
 await expect(current).toHaveAttribute('aria-checked','true')
 await expect(page.getByRole('menuitemradio',{name:original,exact:true})).toBeVisible()
 await page.screenshot({path:'../docs/project-switch.png',fullPage:true})
 await current.click();await expect(page.locator('.projects-page')).toHaveCount(0)
 await page.getByRole('button',{name:'Switch project',exact:true}).click()
 await page.getByRole('menuitemradio',{name:original,exact:true}).click()
 await expect(page.locator('h1')).toHaveText(original)
 await page.getByRole('button',{name:'Switch project',exact:true}).click()
 await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0)
 await page.getByTestId('new-ticket').click();await page.getByLabel('Ticket title').fill('Unsaved idea')
 await page.getByRole('button',{name:'Switch project',exact:true}).click()
 await page.getByRole('menuitemradio',{name:'Dropdown project',exact:true}).click()
 await page.getByRole('button',{name:'Keep editing',exact:true}).click()
 await expect(page.getByLabel('Ticket title')).toHaveValue('Unsaved idea')
 await page.getByRole('button',{name:'Switch project',exact:true}).click()
 await page.getByRole('menuitemradio',{name:'Dropdown project',exact:true}).click()
 await page.getByRole('button',{name:'Discard changes',exact:true}).click()
 await expect(page.locator('h1')).toHaveText('Dropdown project')
 await page.getByRole('button',{name:'Switch project',exact:true}).click()
 await page.getByRole('menuitem',{name:'Manage projects',exact:true}).click()
 await expect(page.locator('.projects-page')).toBeVisible()
})
